name: deployment on server

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu

    steps:
      - uses: actions/checkout@v3

      - name: update bot
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/deploy/vatsimfox && git pull origin main --force && cd /home/deploy/vatsimfox/src
            docker-compose up -d --build
